### PR TITLE
Allow for enhanced object model for an SNS event.

### PR DESCRIPTION
**Pull request by garyd203**
It is possible to specify the name for a serverless-generated SNS topic
by using the `topicName` and `displayName` fields. This means we
should look for topicName even if there is no `arn` field.

https://serverless.com/framework/docs/providers/aws/events/sns#setting-a-display-name

### CODE REVIEW

**Comment by garyd203** [comment]
As discussed, I am not 100% sure if this is the best approach to solving or testing this, but at least this can show what the issue was. Cheers!

**Comment by temyers** [comment]
Thanks,

Sorry, dragged off on other things - I'll try and respond in more detail later this week.

Would you be able to include a sample of the generated cloudformation when performing `sls package`.  This can be added in the tests under 
```
let sampleCompiledCloudformationTemplate = {
Resources:
```

This needs refactoring to separate out the cloudformation for each spec, but will work as a starting point for now.

**Comment by garyd203** [comment]
Hi @temyers , I updated the existing sample cloud formation. Apologies for taking so long to get back to you.

**Comment by temyers** [comment]
Hi @garyd203, no problem at all.  This had dropped off my radar too :)

LGTM!

**Comment by temyers** [comment]
The CI failure is due to missing Snyk token - expected (although I need to look at that for contributions)

**Pull request merged**
